 #Imagen base oficial de Nginx  
FROM nginx:alpine  

# Copiar tu página web al directorio que sirve Nginx
# Dentro de la capeta 'public' estan los archivos de la página web  
COPY public/ /usr/share/nginx/html/  

RUN chmod -R 644 /usr/share/nginx/html/* && \
    chmod 755 /usr/share/nginx/html

# Exponer el puerto estándar de HTTP  
EXPOSE 80  

CMD ["nginx" , "-g", "daemon off;"] 