 #Imagen base oficial de Nginx  
FROM nginx:alpine  

# Copiar tu página web al directorio que sirve Nginx  
COPY public/ /usr/share/nginx/html/  
#COPY ./index.html /usr/share/nginx/html/index.html

# Exponer el puerto estándar de HTTP  
EXPOSE 80  

# Comando por defecto (ya viene configurado en la imagen de Nginx)  
CMD ["nginx", "-g", "daemon off;"] 