version: '3'
tasks:
  clean-namespace:
    desc: Elimina el namespace y todos los recursos asociados
    dir: ./kubernetes
    cmds:
      - kubectl delete namespace dorayakiweb
      - minikube image rm dorayakiweb-service:latest || true
      - minikube image rm dorayakiweb-proxy-service:latest || true

  setup-namespace:
    desc: Crea el namespace de la práctica
    dir: ./kubernetes
    cmds:
      - kubectl apply -f namespace.yaml

  build-dorayakiweb:
    desc: Construye y carga la imagen de dorayakiweb-service en Minikube
    cmds:
      - minikube image build -t dorayakiweb-service:latest ./web/
  
  build-dorayakiweb-proxy:
    desc: Construye y carga la imagen de proxyInverso en Minikube
    cmds:
      - minikube image build -t dorayakiweb-proxy-service:latest ./proxyInverso/

  build-todo:
    desc: Construye y carga todas las imágenes necesarias
    deps:
      - build-dorayakiweb
      - build-dorayakiweb-proxy

  deploy-dorayakiweb:
    desc: Aplica los recursos del dorayakiweb-service
    dir: ./kubernetes
    cmds:
  
      - kubectl apply -f dorayakiweb-deployment.yaml -n dorayakiweb
      - kubectl apply -f dorayakiweb-service.yaml -n dorayakiweb

  deploy-proxyInverso:
    desc: Aplica el Ingress del dorayakiweb-service
    dir: ./kubernetes
    cmds:
      - kubectl apply -f proxyInverso-deployment.yaml -n dorayakiweb
      - kubectl apply -f proxyInverso-service.yaml -n dorayakiweb
  deploy-todo:
    desc: Aplica todos los recursos
    cmds:
      - task: setup-namespace
      - task: build-todo
      - task: deploy-dorayakiweb
      - task: deploy-proxyInverso
